uploads = []

[[generated]]
id = "RZ2ZwUbP4mYklvCnyS5VC"
uri = "file://artifacts/record-you-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "jbMXd5axnL_MWLXab52Wd"
uri = "file://screenshots/expected-phone.jpg"
type = "image"
title = "What the server is serving right now"

[[outputs]]
id = "m2tjUoCGGB9pMMcczYZGO"
uri = "file://screenshots/current-server.jpg"
type = "image"
title = "What the server is serving right now (just screenshotted)"
